language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
branches:
  only:
    - master

before_script:
  - npm i -g @angular/cli

script:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/myport
  on:
    branch: master
